version: "3"
services:
  katan:
    build:
      context: .
      dockerfile: Dockerfile
    links:
      - database
    depends_on:
      - database
    restart: on-failure
    #      - web-ui
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - DB_HOST=database
      - DB_PASS=katan
      - ENV=dev
      - DOCKER_HOST=tcp://localhost:2375
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
#  web-ui:
#    image: ghcr.io/katanpanel/web-ui:main
#    container_name: web-ui
#    restart: always
#    ports:
#      - "80:8081"
#    environment:
#
#    volumes:
#      - "./katan/web-ui:/etc/nginx"
  database:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_PASSWORD=katan