version: "3"
services:
  katan:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: control-panel
    links:
      - database
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=database
      - DB_PASS=katan
      - ENV=dev
      - DOCKER_HOST=tcp://localhost:2375
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./katan/cp:/usr/katan"
  database:
    image: postgres:latest
    container_name: database
    restart: always
    environment:
      - POSTGRES_PASSWORD=katan
    volumes:
      - "./katan/db:/var/lib/postgresql/data"